language: php

php:
  - 7.2
  - 7.3

before_script:
  - composer install --no-interaction --no-suggest --prefer-dist --classmap-authoritative

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)